---
title: "EP09"
author: "Equipo 2"
date: "2024-12-02"
output:
    html_document:
    highlight: tango
    word_document: default
    pdf_document: default
---

```{=html}
<style>
body {
  font-family: 'Calibri', sans-serif;
}
</style>
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo =FALSE, warning=FALSE, message=FALSE}
options(repos = c(CRAN = "https://cran.rstudio.com/"))

if (!requireNamespace('tidyverse', quietly = TRUE)){
  install.packages('tidyverse')
}
library(tidyverse)
if (!requireNamespace('ggpubr', quietly = TRUE)){
  install.packages('ggpubr')
}
library(ggpubr)
if (!requireNamespace('ez', quietly = TRUE)){
  install.packages('ez')
}
library(ez)
if (!requireNamespace('RVAideMemoire', quietly = TRUE)){
  install.packages('RVAideMemoire')
}
library(RVAideMemoire)
if (!requireNamespace('rcompanion', quietly = TRUE)){
  install.packages('rcompanion')
}
library(rcompanion)
if (!requireNamespace('dplyr', quietly = TRUE)){
  install.packages('dplyr')
}
library(dplyr)
if (!requireNamespace('WRS2', quietly = TRUE)){
  install.packages('WRS2')
}
library(WRS2)
```

```{r leer archivo}
datos <- read.csv2("EP09 Datos.csv")
head(datos)
```

```{r semilla}
set.seed(7525)

datos = datos %>% filter(Gender == 1) %>% sample_n(100)
datos[["id"]] = 1:100

i_datos = sample.int(n = 100, size = 70, replace = FALSE)

datos_70 = datos[i_datos,]
datos_30 = datos[-i_datos,]

predictores = sample(colnames(datos), 8)

print(predictores)

modeloSimple = lm(Weight ~ Waist.Girth, data = datos_70)
print(summary(modeloSimple))


```

